@domain=http://localhost:5000

### GET links
GET {{domain}}/api/links

### GET single link
GET {{domain}}/api/links/1

### POST link
POST {{domain}}/api/links
Content-Type: application/json

{
    "userId": 1,
    "link":"http://wa.me/5596991586908",
    "title": "wpp leo"
}

### PUT link
PUT {{domain}}/api/links/1
Content-Type: application/json

{
    "title":"link 1"
}

### DELETE link
DELETE {{domain}}/api/links/1
